# Home Decor Store - Student Practice Notebook

Dataset file: `08_home_decor_store.csv`

Solve each task in the empty code cell below it.

## Task 1

Load the dataset into a pandas DataFrame.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("08_home_decor_store.csv")

## Task 2

Display the first 10 rows of the DataFrame.

In [3]:
df.head(10)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value
0,08ORD100522,2025-06-02,Interior Designer,West,Decor Pieces,Cash on Delivery,3,2003.04,24,4566.93
1,08ORD100738,2025-01-08,Interior Designer,West,Wall Art,Debit Card,3,6131.91,12,16188.24
2,08ORD100741,2025-09-24,Residential,West,Wall Art,Cash on Delivery,2,10940.32,6,20567.80
3,08ORD100661,2024-09-06,Residential,South,Rugs,Debit Card,1,9917.44,14,8529.00
4,08ORD100412,2024-03-25,Corporate,West,Wall Art,Debit Card,1,4145.92,10,3731.33
5,08ORD100679,2024-11-19,Residential,Central,Curtains,Debit Card,2,17048.48,35,22163.02
6,08ORD100627,2025-10-08,Residential,Central,Decor Pieces,Debit Card,3,1782.65,0,5347.95
7,08ORD100514,2025-03-09,Gift Buyer,Central,Curtains,UPI,2,13079.27,8,24065.86
8,08ORD100860,2024-12-01,Gift Buyer,East,Wall Art,EMI,1,10018.63,38,6211.55
9,08ORD100137,2025-03-06,Corporate,East,Rugs,Credit Card,2,14365.42,38,17813.12

## Task 3

Display the last 7 rows of the DataFrame.

In [4]:
df.tail(7)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value
993,08ORD100701,2024-03-20,Corporate,North,Rugs,Credit Card,3,5703.40,15,14543.67
994,08ORD100072,2024-06-02,Residential,West,Lighting,Cash on Delivery,1,12167.00,6,11436.98
995,08ORD100107,2025-08-18,Interior Designer,West,Decor Pieces,Debit Card,2,3384.99,8,6228.38
996,08ORD100271,2025-05-15,Corporate,Central,Rugs,UPI,1,2269.52,10,2042.57
997,08ORD100861,2024-09-12,Interior Designer,North,Wall Art,UPI,1,13990.14,1,13850.24
998,08ORD100436,2024-05-15,Corporate,West,Curtains,EMI,1,16820.17,29,11942.32
999,08ORD100103,2025-05-03,Interior Designer,East,Rugs,UPI,3,21462.87,23,49579.23

## Task 4

Check the shape of the DataFrame.

In [5]:
df.shape

(1000, 10)

## Task 5

List all column names.

In [9]:
columns = df.columns.tolist()
print(columns)

['Order_ID', 'Order_Date', 'Customer_Segment', 'Region', 'Product_Category', 'Payment_Method', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Order_Value']

## Task 6

Check the data types of all columns.

In [20]:
df.dtypes

Order_ID                str
Order_Date              str
Customer_Segment        str
Region                  str
Product_Category        str
Payment_Method          str
Quantity              int64
Unit_Price          float64
Discount_Percent      int64
Order_Value         float64
dtype: object

## Task 7

Display basic information using info().

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1000 non-null   str
 1   Order_Date        1000 non-null   str
 2   Customer_Segment  1000 non-null   str
 3   Region            1000 non-null   str
 4   Product_Category  1000 non-null   str
 5   Payment_Method    1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Unit_Price        1000 non-null   float64
 8   Discount_Percent  1000 non-null   int64
 9   Order_Value       1000 non-null   float64
dtypes: float64(2), int64(2), str(6)
memory usage: 78.3 KB

## Task 8

Generate summary statistics for numerical columns.

In [16]:
df.describe()

          Quantity    Unit_Price  Discount_Percent   Order_Value
count  1000.000000   1000.000000       1000.000000   1000.000000
mean      2.001000  12278.096220         22.334000  18932.113760
std       1.088202   7232.054923         13.286722  16427.712464
min       1.000000    151.330000          0.000000    119.890000
25%       1.000000   6196.745000         10.750000   7015.832500
50%       2.000000  11903.120000         22.000000  13845.610000
75%       3.000000  18660.295000         34.000000  26476.410000
max       4.000000  24998.310000         45.000000  97690.510000

## Task 9

Generate summary statistics for categorical columns.

In [19]:
df.describe(include='str')

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method
count,1000,1000,1000,1000,1000,1000
unique,1000,558,4,5,5,5
top,08ORD100522,2024-12-30,Residential,Central,Rugs,UPI
freq,1,6,264,224,219,221

## Task 10

Check whether the DataFrame contains any missing values.

In [26]:
df.isna()

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False

## Task 11

Count the missing values in each column.

In [28]:
df.isna().sum()

Order_ID            0
Order_Date          0
Customer_Segment    0
Region              0
Product_Category    0
Payment_Method      0
Quantity            0
Unit_Price          0
Discount_Percent    0
Order_Value         0
dtype: int64

## Task 12

Check whether there are any duplicate rows.

In [30]:
df.duplicated().any()

np.False_

## Task 13

Count the duplicate rows in the DataFrame.

In [31]:
df.duplicated().sum()

np.int64(0)

## Task 14

Drop duplicate rows if any exist.

In [36]:
newDf = df.drop_duplicates()
print(newDf)

        Order_ID  Order_Date   Customer_Segment   Region Product_Category  \
0    08ORD100522  2025-06-02  Interior Designer     West     Decor Pieces
1    08ORD100738  2025-01-08  Interior Designer     West         Wall Art
2    08ORD100741  2025-09-24        Residential     West         Wall Art
3    08ORD100661  2024-09-06        Residential    South             Rugs
4    08ORD100412  2024-03-25          Corporate     West         Wall Art
..           ...         ...                ...      ...              ...
995  08ORD100107  2025-08-18  Interior Designer     West     Decor Pieces
996  08ORD100271  2025-05-15          Corporate  Central             Rugs
997  08ORD100861  2024-09-12  Interior Designer    North         Wall Art
998  08ORD100436  2024-05-15          Corporate     West         Curtains
999  08ORD100103  2025-05-03  Interior Designer     East             Rugs

       Payment_Method  Quantity  Unit_Price  Discount_Percent  Order_Value
0    Cash on Delivery         3     2003.04                24      4566.93
1          Debit Card         3     6131.91                12     16188.24
2    Cash on Delivery         2    10940.32                 6     20567.80
3          Debit Card         1     9917.44                14      8529.00
4          Debit Card         1     4145.92                10      3731.33
..                ...       ...         ...               ...          ...
995        Debit Card         2     3384.99                 8      6228.38
996               UPI         1     2269.52                10      2042.57
997               UPI         1    13990.14                 1     13850.24
998               EMI         1    16820.17                29     11942.32
999               UPI         3    21462.87                23     49579.23

[1000 rows x 10 columns]

## Task 15

Convert the Order_Date column to datetime format.

In [39]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
print(df['Order_Date'].dtypes)

datetime64[us]

## Task 16

Extract only the year from Order_Date into a new column named Order_Year.

In [44]:
df['Order_Year'] = df['Order_Date'].dt.year
print(df[['Order_ID','Order_Year']].head(8))

      Order_ID  Order_Year
0  08ORD100522        2025
1  08ORD100738        2025
2  08ORD100741        2025
3  08ORD100661        2024
4  08ORD100412        2024
5  08ORD100679        2024
6  08ORD100627        2025
7  08ORD100514        2025

## Task 17

Extract the month name from Order_Date into a new column named Order_Month.

In [48]:
df['Order_Month'] = df['Order_Date'].dt.month
print(df[['Order_ID','Order_Month']].head(10))

      Order_ID  Order_Month
0  08ORD100522            6
1  08ORD100738            1
2  08ORD100741            9
3  08ORD100661            9
4  08ORD100412            3
5  08ORD100679           11
6  08ORD100627           10
7  08ORD100514            3
8  08ORD100860           12
9  08ORD100137            3

## Task 18

Extract the weekday name from Order_Date into a new column named Order_Day.

In [47]:
df['Order_Day'] = df['Order_Date'].dt.weekday
print(df[['Order_ID','Order_Day']].head(10))

      Order_ID  Order_Day
0  08ORD100522          0
1  08ORD100738          2
2  08ORD100741          2
3  08ORD100661          4
4  08ORD100412          0
5  08ORD100679          1
6  08ORD100627          2
7  08ORD100514          6
8  08ORD100860          6
9  08ORD100137          3

## Task 19

Display a random sample of 12 rows.

In [49]:
df.sample(12,random_state=42)  #it displays the random 12 samples from the dataset

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
521,08ORD100667,2024-10-31,Interior Designer,North,Rugs,Cash on Delivery,1,1084.28,15,921.64,2024,10,3
737,08ORD100130,2024-06-01,Residential,Central,Rugs,Debit Card,2,18385.72,10,33094.30,2024,6,5
740,08ORD100785,2024-08-27,Corporate,North,Rugs,Debit Card,2,17382.48,21,27464.32,2024,8,1
660,08ORD100153,2024-03-23,Gift Buyer,North,Lighting,Debit Card,1,12024.63,0,12024.63,2024,3,5
411,08ORD100921,2025-10-31,Corporate,North,Rugs,Credit Card,1,10252.83,24,7792.15,2025,10,4
678,08ORD100946,2025-01-06,Residential,Central,Decor Pieces,UPI,1,6579.16,17,5460.70,2025,1,0
626,08ORD100049,2025-05-30,Corporate,East,Wall Art,Debit Card,1,4830.09,12,4250.48,2025,5,4
513,08ORD100016,2024-08-20,Residential,East,Lighting,Debit Card,1,24650.32,27,17994.73,2024,8,1
859,08ORD100773,2025-04-26,Residential,North,Wall Art,EMI,4,5422.47,28,15616.71,2025,4,5
136,08ORD100121,2024-12-19,Gift Buyer,Central,Rugs,Cash on Delivery,1,12662.42,14,10889.68,2024,12,3
811,08ORD100171,2024-03-07,Gift Buyer,East,Lighting,EMI,1,19333.03,45,10633.17,2024,3,3
76,08ORD100653,2025-01-16,Corporate,East,Lighting,Credit Card,1,13825.10,16,11613.08,2025,1,3

## Task 20

Rename Discount_Percent to Discount.

In [52]:
df = df.rename(columns={'Discount_Percent':"Discount"})
df.columns.tolist()

['Order_ID',
 'Order_Date',
 'Customer_Segment',
 'Region',
 'Product_Category',
 'Payment_Method',
 'Quantity',
 'Unit_Price',
 'Discount',
 'Order_Value',
 'Order_Year',
 'Order_Month',
 'Order_Day',
 'Discount']

## Task 21

Change the column name back from Discount to Discount_Percent.

In [54]:
df = df.rename(columns={'Discount':'Discount_Percent'})
df.columns.tolist()

['Order_ID',
 'Order_Date',
 'Customer_Segment',
 'Region',
 'Product_Category',
 'Payment_Method',
 'Quantity',
 'Unit_Price',
 'Discount_Percent',
 'Order_Value',
 'Order_Year',
 'Order_Month',
 'Order_Day',
 'Discount_Percent']

## Task 22

Set Order_ID as the index.

In [62]:
df.set_index('Order_ID')
df.head(10)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Discount_Percent
0,08ORD100522,2025-06-02,Interior Designer,West,Decor Pieces,Cash on Delivery,3,2003.04,24,4566.93,2025,6,0,24
1,08ORD100738,2025-01-08,Interior Designer,West,Wall Art,Debit Card,3,6131.91,12,16188.24,2025,1,2,12
2,08ORD100741,2025-09-24,Residential,West,Wall Art,Cash on Delivery,2,10940.32,6,20567.80,2025,9,2,6
3,08ORD100661,2024-09-06,Residential,South,Rugs,Debit Card,1,9917.44,14,8529.00,2024,9,4,14
4,08ORD100412,2024-03-25,Corporate,West,Wall Art,Debit Card,1,4145.92,10,3731.33,2024,3,0,10
5,08ORD100679,2024-11-19,Residential,Central,Curtains,Debit Card,2,17048.48,35,22163.02,2024,11,1,35
6,08ORD100627,2025-10-08,Residential,Central,Decor Pieces,Debit Card,3,1782.65,0,5347.95,2025,10,2,0
7,08ORD100514,2025-03-09,Gift Buyer,Central,Curtains,UPI,2,13079.27,8,24065.86,2025,3,6,8
8,08ORD100860,2024-12-01,Gift Buyer,East,Wall Art,EMI,1,10018.63,38,6211.55,2024,12,6,38
9,08ORD100137,2025-03-06,Corporate,East,Rugs,Credit Card,2,14365.42,38,17813.12,2025,3,3,38

## Task 23

Reset the index back to default integer index.

In [63]:
df.reset_index()
df.head(10)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Discount_Percent
0,08ORD100522,2025-06-02,Interior Designer,West,Decor Pieces,Cash on Delivery,3,2003.04,24,4566.93,2025,6,0,24
1,08ORD100738,2025-01-08,Interior Designer,West,Wall Art,Debit Card,3,6131.91,12,16188.24,2025,1,2,12
2,08ORD100741,2025-09-24,Residential,West,Wall Art,Cash on Delivery,2,10940.32,6,20567.80,2025,9,2,6
3,08ORD100661,2024-09-06,Residential,South,Rugs,Debit Card,1,9917.44,14,8529.00,2024,9,4,14
4,08ORD100412,2024-03-25,Corporate,West,Wall Art,Debit Card,1,4145.92,10,3731.33,2024,3,0,10
5,08ORD100679,2024-11-19,Residential,Central,Curtains,Debit Card,2,17048.48,35,22163.02,2024,11,1,35
6,08ORD100627,2025-10-08,Residential,Central,Decor Pieces,Debit Card,3,1782.65,0,5347.95,2025,10,2,0
7,08ORD100514,2025-03-09,Gift Buyer,Central,Curtains,UPI,2,13079.27,8,24065.86,2025,3,6,8
8,08ORD100860,2024-12-01,Gift Buyer,East,Wall Art,EMI,1,10018.63,38,6211.55,2024,12,6,38
9,08ORD100137,2025-03-06,Corporate,East,Rugs,Credit Card,2,14365.42,38,17813.12,2025,3,3,38

## Task 24

Sort the DataFrame by Order_Value in descending order.

In [66]:
sortedValues = df.sort_values('Order_Value',ascending=False)
print(sortedValues.head(8))

        Order_ID Order_Date   Customer_Segment Region Product_Category  \
175  08ORD100364 2024-04-19          Corporate   East             Rugs
486  08ORD100043 2025-12-04  Interior Designer   West         Wall Art
928  08ORD100340 2025-01-07  Interior Designer  North             Rugs
663  08ORD100756 2024-03-26  Interior Designer  North     Decor Pieces
38   08ORD100902 2025-04-07  Interior Designer  North             Rugs
303  08ORD100423 2024-04-11  Interior Designer   West         Wall Art
579  08ORD100626 2024-03-26        Residential   East     Decor Pieces
265  08ORD100869 2025-07-08  Interior Designer   West             Rugs

    Payment_Method  Quantity  Unit_Price  Discount_Percent  Order_Value  \
175            UPI         4    24669.32                 1     97690.51
486            EMI         4    23245.34                 7     86472.66
928    Credit Card         4    23876.54                10     85955.54
663     Debit Card         4    22725.08                13     79083.28
38             UPI         4    22979.15                15     78129.11
303            UPI         4    19171.97                 1     75921.00
579     Debit Card         4    24633.21                24     74884.96
265    Credit Card         4    23113.30                20     73962.56

     Order_Year  Order_Month  Order_Day  Discount_Percent
175        2024            4          4                 1
486        2025           12          3                 7
928        2025            1          1                10
663        2024            3          1                13
38         2025            4          0                15
303        2024            4          3                 1
579        2024            3          1                24
265        2025            7          1                20

## Task 25

Sort the DataFrame by Quantity ascending and Unit_Price descending.

In [70]:
df.sort_values(['Quantity','Unit_Price'],ascending=[True,False]).head(9)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Discount_Percent
909,08ORD100477,2025-06-25,Gift Buyer,North,Curtains,UPI,1,24998.31,16,20998.58,2025,6,2,16
800,08ORD100557,2025-02-07,Interior Designer,North,Curtains,Debit Card,1,24961.07,19,20218.47,2025,2,4,19
552,08ORD100694,2025-05-29,Interior Designer,Central,Curtains,Cash on Delivery,1,24956.49,12,21961.71,2025,5,3,12
240,08ORD100004,2025-08-18,Corporate,South,Curtains,Cash on Delivery,1,24945.31,30,17461.72,2025,8,0,30
42,08ORD100313,2024-02-29,Interior Designer,Central,Lighting,Debit Card,1,24872.14,26,18405.38,2024,2,3,26
673,08ORD100673,2024-06-16,Gift Buyer,West,Lighting,Debit Card,1,24820.33,15,21097.28,2024,6,6,15
226,08ORD100545,2024-05-15,Gift Buyer,North,Curtains,Credit Card,1,24797.87,10,22318.08,2024,5,2,10
868,08ORD100063,2024-09-09,Corporate,South,Curtains,Cash on Delivery,1,24796.11,25,18597.08,2024,9,0,25
191,08ORD100830,2024-12-14,Gift Buyer,East,Rugs,Debit Card,1,24671.52,1,24424.80,2024,12,5,1

## Task 26

Filter all rows where Region is North.

In [72]:
df.query('Region == "North"').head(20)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Discount_Percent
10,08ORD100812,2024-12-22,Interior Designer,North,Curtains,Credit Card,1,5655.95,44,3167.33,2024,12,6,44
14,08ORD100939,2025-01-16,Interior Designer,North,Lighting,UPI,1,22495.05,3,21820.20,2025,1,3,3
19,08ORD100320,2025-09-04,Corporate,North,Decor Pieces,Credit Card,3,9575.78,4,27578.25,2025,9,3,4
25,08ORD100236,2024-07-24,Interior Designer,North,Lighting,Credit Card,2,20904.13,26,30938.11,2024,7,2,26
26,08ORD100102,2024-04-16,Corporate,North,Curtains,EMI,1,13152.82,38,8154.75,2024,4,1,38
37,08ORD100585,2024-10-27,Gift Buyer,North,Lighting,Debit Card,1,18725.85,36,11984.54,2024,10,6,36
38,08ORD100902,2025-04-07,Interior Designer,North,Rugs,UPI,4,22979.15,15,78129.11,2025,4,0,15
44,08ORD100300,2025-12-29,Residential,North,Wall Art,Cash on Delivery,1,3688.50,43,2102.45,2025,12,0,43
46,08ORD100925,2025-08-20,Corporate,North,Curtains,Debit Card,4,20329.41,32,55296.00,2025,8,2,32
52,08ORD100262,2024-05-18,Residential,North,Wall Art,Debit Card,2,12211.05,34,16118.59,2024,5,5,34
65,08ORD100693,2024-01-09,Interior Designer,North,Lighting,EMI,1,679.45,33,455.23,2024,1,1,33
66,08ORD100663,2025-03-26,Interior Designer,North,Rugs,EMI,1,11707.34,21,9248.80,2025,3,2,21
67,08ORD100867,2024-06-12,Residential,North,Curtains,UPI,2,151.33,34,199.76,2024,6,2,34
73,08ORD100742,2024-04-26,Residential,North,Lighting,Cash on Delivery,4,13148.12,30,36814.74,2024,4,4,30
75,08ORD100290,2024-04-05,Residential,North,Curtains,Credit Card,1,24372.63,10,21935.37,2024,4,4,10
79,08ORD100308,2025-10-08,Interior Designer,North,Curtains,Cash on Delivery,2,4935.22,10,8883.40,2025,10,2,10
82,08ORD100276,2024-05-01,Gift Buyer,North,Wall Art,EMI,4,10218.42,6,38421.26,2024,5,2,6
84,08ORD100319,2025-03-23,Gift Buyer,North,Rugs,Cash on Delivery,1,11003.83,16,9243.22,2025,3,6,16
86,08ORD100999,2024-03-24,Interior Designer,North,Lighting,Debit Card,2,14448.99,30,20228.59,2024,3,6,30
91,08ORD100452,2024-09-02,Corporate,North,Curtains,UPI,1,21333.13,20,17066.50,2024,9,0,20

## Task 27

Filter all rows where Payment_Method is UPI.

In [73]:
df.query('Payment_Method == "UPI"').head(15)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Discount_Percent
7,08ORD100514,2025-03-09,Gift Buyer,Central,Curtains,UPI,2,13079.27,8,24065.86,2025,3,6,8
13,08ORD100974,2025-06-18,Residential,East,Lighting,UPI,1,603.64,39,368.22,2025,6,2,39
14,08ORD100939,2025-01-16,Interior Designer,North,Lighting,UPI,1,22495.05,3,21820.20,2025,1,3,3
17,08ORD100884,2025-07-17,Gift Buyer,West,Decor Pieces,UPI,3,16775.58,28,36235.25,2025,7,3,28
20,08ORD100550,2024-12-24,Corporate,Central,Wall Art,UPI,1,22672.15,19,18364.44,2024,12,1,19
21,08ORD100175,2025-07-08,Corporate,South,Wall Art,UPI,4,11316.98,22,35308.98,2025,7,1,22
24,08ORD100211,2024-09-15,Gift Buyer,West,Decor Pieces,UPI,1,1553.60,40,932.16,2024,9,6,40
35,08ORD100199,2025-01-30,Residential,East,Rugs,UPI,4,19255.78,13,67010.11,2025,1,3,13
36,08ORD100688,2025-02-08,Corporate,Central,Decor Pieces,UPI,3,23882.54,34,47287.43,2025,2,5,34
38,08ORD100902,2025-04-07,Interior Designer,North,Rugs,UPI,4,22979.15,15,78129.11,2025,4,0,15
43,08ORD100975,2025-11-04,Gift Buyer,South,Lighting,UPI,1,13735.78,1,13598.42,2025,11,1,1
49,08ORD100838,2024-11-14,Interior Designer,South,Lighting,UPI,3,9804.60,36,18824.83,2024,11,3,36
51,08ORD100880,2025-06-07,Corporate,Central,Wall Art,UPI,2,799.28,18,1310.82,2025,6,5,18
53,08ORD100579,2025-02-16,Corporate,West,Decor Pieces,UPI,1,17266.94,33,11568.85,2025,2,6,33
60,08ORD100297,2025-09-02,Residential,Central,Rugs,UPI,2,620.67,17,1030.31,2025,9,1,17

## Task 28

Filter all rows where Quantity is greater than 3.

In [75]:
df.query('Quantity > 3').head(13)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Discount_Percent
21,08ORD100175,2025-07-08,Corporate,South,Wall Art,UPI,4,11316.98,22,35308.98,2025,7,1,22
23,08ORD100528,2025-09-30,Gift Buyer,Central,Rugs,Credit Card,4,2872.24,34,7582.71,2025,9,1,34
29,08ORD100948,2025-02-15,Interior Designer,Central,Lighting,Debit Card,4,18479.31,36,47307.03,2025,2,5,36
30,08ORD100347,2025-08-19,Interior Designer,West,Curtains,Debit Card,4,2678.46,0,10713.84,2025,8,1,0
35,08ORD100199,2025-01-30,Residential,East,Rugs,UPI,4,19255.78,13,67010.11,2025,1,3,13
38,08ORD100902,2025-04-07,Interior Designer,North,Rugs,UPI,4,22979.15,15,78129.11,2025,4,0,15
46,08ORD100925,2025-08-20,Corporate,North,Curtains,Debit Card,4,20329.41,32,55296.00,2025,8,2,32
50,08ORD100571,2025-11-20,Interior Designer,West,Rugs,Cash on Delivery,4,20552.53,27,60013.39,2025,11,3,27
69,08ORD100544,2025-10-02,Interior Designer,West,Rugs,UPI,4,16329.28,6,61398.09,2025,10,3,6
73,08ORD100742,2024-04-26,Residential,North,Lighting,Cash on Delivery,4,13148.12,30,36814.74,2024,4,4,30
82,08ORD100276,2024-05-01,Gift Buyer,North,Wall Art,EMI,4,10218.42,6,38421.26,2024,5,2,6
87,08ORD100715,2025-10-23,Corporate,Central,Wall Art,UPI,4,4969.72,44,11132.17,2025,10,3,44
97,08ORD100089,2024-02-01,Interior Designer,South,Wall Art,Cash on Delivery,4,18484.50,25,55453.50,2024,2,3,25

## Task 29

Filter all rows where Order_Value is above 5000.

In [80]:
df[df['Order_Value'] > 5000].head(20)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Discount_Percent
1,08ORD100738,2025-01-08,Interior Designer,West,Wall Art,Debit Card,3,6131.91,12,16188.24,2025,1,2,12
2,08ORD100741,2025-09-24,Residential,West,Wall Art,Cash on Delivery,2,10940.32,6,20567.80,2025,9,2,6
3,08ORD100661,2024-09-06,Residential,South,Rugs,Debit Card,1,9917.44,14,8529.00,2024,9,4,14
5,08ORD100679,2024-11-19,Residential,Central,Curtains,Debit Card,2,17048.48,35,22163.02,2024,11,1,35
6,08ORD100627,2025-10-08,Residential,Central,Decor Pieces,Debit Card,3,1782.65,0,5347.95,2025,10,2,0
7,08ORD100514,2025-03-09,Gift Buyer,Central,Curtains,UPI,2,13079.27,8,24065.86,2025,3,6,8
8,08ORD100860,2024-12-01,Gift Buyer,East,Wall Art,EMI,1,10018.63,38,6211.55,2024,12,6,38
9,08ORD100137,2025-03-06,Corporate,East,Rugs,Credit Card,2,14365.42,38,17813.12,2025,3,3,38
11,08ORD100077,2025-07-18,Gift Buyer,East,Rugs,Credit Card,1,8583.19,9,7810.70,2025,7,4,9
12,08ORD100637,2025-10-10,Residential,East,Rugs,Credit Card,1,22898.74,33,15342.16,2025,10,4,33
14,08ORD100939,2025-01-16,Interior Designer,North,Lighting,UPI,1,22495.05,3,21820.20,2025,1,3,3
15,08ORD100900,2025-01-02,Gift Buyer,East,Decor Pieces,Debit Card,2,24009.62,32,32653.08,2025,1,3,32
16,08ORD100281,2025-02-03,Interior Designer,East,Decor Pieces,EMI,1,13795.77,26,10208.87,2025,2,0,26
17,08ORD100884,2025-07-17,Gift Buyer,West,Decor Pieces,UPI,3,16775.58,28,36235.25,2025,7,3,28
18,08ORD100762,2025-10-20,Interior Designer,West,Rugs,Cash on Delivery,2,18761.58,35,24390.05,2025,10,0,35
19,08ORD100320,2025-09-04,Corporate,North,Decor Pieces,Credit Card,3,9575.78,4,27578.25,2025,9,3,4
20,08ORD100550,2024-12-24,Corporate,Central,Wall Art,UPI,1,22672.15,19,18364.44,2024,12,1,19
21,08ORD100175,2025-07-08,Corporate,South,Wall Art,UPI,4,11316.98,22,35308.98,2025,7,1,22
22,08ORD100372,2024-01-23,Gift Buyer,South,Wall Art,Cash on Delivery,1,12617.23,18,10346.13,2024,1,1,18
23,08ORD100528,2025-09-30,Gift Buyer,Central,Rugs,Credit Card,4,2872.24,34,7582.71,2025,9,1,34

## Task 30

Filter rows where Discount_Percent is between 10 and 20.

In [87]:
df[df['Discount_Percent'].between(10,20)].head()

AttributeError: 'DataFrame' object has no attribute 'between'

## Task 31

Filter rows where Product_Category belongs to a given list of two categories.

## Task 32

Find all unique values in Customer_Segment.

In [89]:
df['Customer_Segment'].unique().tolist()

['Interior Designer', 'Residential', 'Corporate', 'Gift Buyer']

## Task 33

Count the number of unique values in Product_Category.

In [90]:
df['Product_Category'].unique().tolist()

['Decor Pieces', 'Wall Art', 'Rugs', 'Curtains', 'Lighting']

## Task 34

Display value counts for Region.

In [91]:
df['Region'].value_counts()

Region
Central    224
North      210
West       204
South      184
East       178
Name: count, dtype: int64

## Task 35

Display value counts for Payment_Method.

In [92]:
df['Payment_Method'].value_counts()

Payment_Method
UPI                 221
Debit Card          209
Cash on Delivery    194
EMI                 190
Credit Card         186
Name: count, dtype: int64

## Task 36

Find the minimum, maximum, and mean of Unit_Price.

In [94]:
df['Unit_Price'].dropna().min(),df['Unit_Price'].dropna().max(),df['Unit_Price'].dropna().mean()

(np.float64(151.33), np.float64(24998.31), np.float64(12278.09622))

## Task 37

Find the total sum of Order_Value.

In [99]:
df['Order_Value'].dropna().sum()

np.float64(18932113.759999998)

## Task 38

Find the median of Quantity.

In [100]:
df['Quantity'].dropna().median()

np.float64(2.0)

## Task 39

Find the standard deviation of Order_Value.

In [101]:
df['Order_Value'].dropna().std()

np.float64(16427.712463714917)

## Task 40

Create a new column Gross_Value as Quantity multiplied by Unit_Price.

In [104]:
df['Gross_Value'] = df['Quantity'] * df['Unit_Price']
print(df[['Gross_Value','Quantity','Unit_Price']].head(15))

    Gross_Value  Quantity  Unit_Price
0       6009.12         3     2003.04
1      18395.73         3     6131.91
2      21880.64         2    10940.32
3       9917.44         1     9917.44
4       4145.92         1     4145.92
5      34096.96         2    17048.48
6       5347.95         3     1782.65
7      26158.54         2    13079.27
8      10018.63         1    10018.63
9      28730.84         2    14365.42
10      5655.95         1     5655.95
11      8583.19         1     8583.19
12     22898.74         1    22898.74
13       603.64         1      603.64
14     22495.05         1    22495.05

## Task 41

Verify whether Gross_Value and Order_Value are consistent after discount calculation.

## Task 42

Create a new column Discount_Amount.

In [108]:
df['Discount_Amount'] = (df['Gross_Value'] - df['Order_Value']).round(2)
print(df[['Gross_Value','Order_Value','Discount_Amount']].head(10))

   Gross_Value  Order_Value  Discount_Amount
0      6009.12      4566.93          1442.19
1     18395.73     16188.24          2207.49
2     21880.64     20567.80          1312.84
3      9917.44      8529.00          1388.44
4      4145.92      3731.33           414.59
5     34096.96     22163.02         11933.94
6      5347.95      5347.95             0.00
7     26158.54     24065.86          2092.68
8     10018.63      6211.55          3807.08
9     28730.84     17813.12         10917.72

## Task 43

Create a new column High_Value_Order where Order_Value > 5000 is Yes otherwise No.

In [109]:
df['High_Value_Order'] = np.where(df['Order_Value'] > 5000, 'Yes', 'No')
print(df['High_Value_Order'].head(10))

0     No
1    Yes
2    Yes
3    Yes
4     No
5    Yes
6    Yes
7    Yes
8    Yes
9    Yes
Name: High_Value_Order, dtype: str

## Task 44

Use apply() to categorize Unit_Price into Low, Medium, High.

## Task 45

Find the top 10 highest Order_Value rows.

In [112]:
df.nlargest(10,'Order_Value')

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Discount_Percent,Gross_Value,Discount_Amount,High_Value_Order
175,08ORD100364,2024-04-19,Corporate,East,Rugs,UPI,4,24669.32,1,97690.51,2024,4,4,1,98677.28,986.77,Yes
486,08ORD100043,2025-12-04,Interior Designer,West,Wall Art,EMI,4,23245.34,7,86472.66,2025,12,3,7,92981.36,6508.70,Yes
928,08ORD100340,2025-01-07,Interior Designer,North,Rugs,Credit Card,4,23876.54,10,85955.54,2025,1,1,10,95506.16,9550.62,Yes
663,08ORD100756,2024-03-26,Interior Designer,North,Decor Pieces,Debit Card,4,22725.08,13,79083.28,2024,3,1,13,90900.32,11817.04,Yes
38,08ORD100902,2025-04-07,Interior Designer,North,Rugs,UPI,4,22979.15,15,78129.11,2025,4,0,15,91916.60,13787.49,Yes
303,08ORD100423,2024-04-11,Interior Designer,West,Wall Art,UPI,4,19171.97,1,75921.00,2024,4,3,1,76687.88,766.88,Yes
579,08ORD100626,2024-03-26,Residential,East,Decor Pieces,Debit Card,4,24633.21,24,74884.96,2024,3,1,24,98532.84,23647.88,Yes
265,08ORD100869,2025-07-08,Interior Designer,West,Rugs,Credit Card,4,23113.30,20,73962.56,2025,7,1,20,92453.20,18490.64,Yes
930,08ORD100565,2025-01-21,Gift Buyer,Central,Decor Pieces,UPI,4,20772.89,11,73951.49,2025,1,1,11,83091.56,9140.07,Yes
890,08ORD100749,2024-11-15,Corporate,East,Lighting,UPI,4,23122.01,24,70290.91,2024,11,4,24,92488.04,22197.13,Yes

## Task 46

Find the bottom 10 lowest Order_Value rows.

In [113]:
df.nsmallest(10,'Order_Value')

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Discount_Percent,Gross_Value,Discount_Amount,High_Value_Order
974,08ORD100414,2024-11-06,Gift Buyer,East,Rugs,Credit Card,1,164.23,27,119.89,2024,11,2,27,164.23,44.34,No
937,08ORD100388,2024-12-16,Interior Designer,South,Decor Pieces,Debit Card,1,184.84,26,136.78,2024,12,0,26,184.84,48.06,No
168,08ORD100315,2024-02-28,Interior Designer,North,Decor Pieces,UPI,1,199.31,17,165.43,2024,2,2,17,199.31,33.88,No
112,08ORD100986,2025-06-27,Interior Designer,South,Wall Art,Credit Card,1,199.09,7,185.15,2025,6,4,7,199.09,13.94,No
67,08ORD100867,2024-06-12,Residential,North,Curtains,UPI,2,151.33,34,199.76,2024,6,2,34,302.66,102.90,No
876,08ORD100065,2025-07-17,Corporate,North,Curtains,Debit Card,1,398.02,37,250.75,2025,7,3,37,398.02,147.27,No
446,08ORD100634,2024-05-06,Corporate,Central,Lighting,Credit Card,2,184.89,31,255.15,2024,5,0,31,369.78,114.63,No
200,08ORD100030,2025-03-31,Gift Buyer,Central,Decor Pieces,Credit Card,2,244.06,30,341.68,2025,3,0,30,488.12,146.44,No
13,08ORD100974,2025-06-18,Residential,East,Lighting,UPI,1,603.64,39,368.22,2025,6,2,39,603.64,235.42,No
402,08ORD100540,2025-11-14,Residential,East,Rugs,UPI,2,253.52,26,375.21,2025,11,4,26,507.04,131.83,No

## Task 47

Group by Region and calculate average Order_Value.

In [114]:
df.groupby('Region')['Order_Value'].mean()

Region
Central    18050.488705
East       18898.072135
North      19630.310190
South      17350.976304
West       20637.267990
Name: Order_Value, dtype: float64

## Task 48

Group by Product_Category and calculate total sales.

In [117]:
df.groupby('Product_Category')['Order_Value'].sum().sort_values(ascending=True)

Product_Category
Lighting        3386410.47
Decor Pieces    3528975.55
Curtains        3731679.30
Wall Art        3785798.80
Rugs            4499249.64
Name: Order_Value, dtype: float64

## Task 49

Group by Payment_Method and calculate total Quantity sold.

In [118]:
df.groupby('Payment_Method')['Quantity'].sum().sort_values(ascending=True)

Payment_Method
Cash on Delivery    361
Credit Card         384
EMI                 389
Debit Card          417
UPI                 450
Name: Quantity, dtype: int64

## Task 50

Group by Customer_Segment and calculate average discount percentage.

In [121]:
df.groupby('Customer_Segment')['Discount_Percent'].mean()

                   Discount_Percent  Discount_Percent
Customer_Segment
Corporate                 22.470339         22.470339
Gift Buyer                22.520661         22.520661
Interior Designer         21.515504         21.515504
Residential               22.840909         22.840909

## Task 51

Perform multi-level grouping by Region and Product_Category and compute total Order_Value.

In [122]:
df.groupby(['Region','Product_Category'])['Order_Value'].sum().sort_values(ascending=True)

Region   Product_Category
South    Decor Pieces         453106.08
East     Curtains             471943.61
         Wall Art             506987.96
North    Lighting             559764.69
Central  Lighting             618653.39
South    Curtains             620297.47
         Rugs                 641889.25
         Wall Art             691788.92
West     Lighting             694381.07
East     Decor Pieces         707885.04
West     Decor Pieces         708420.16
East     Lighting             728113.40
Central  Rugs                 768792.49
         Decor Pieces         774145.25
North    Curtains             779482.60
South    Lighting             785497.92
West     Curtains             790724.59
North    Wall Art             811549.73
Central  Wall Art             812487.31
North    Decor Pieces         885419.02
East     Rugs                 948926.83
West     Wall Art             962984.88
         Rugs                1053491.97
Central  Curtains            1069231.03
North    Rugs                1086149.10
Name: Order_Value, dtype: float64

## Task 52

Aggregate Quantity, Unit_Price, and Order_Value with multiple statistics using agg().

In [124]:
df[['Quantity','Unit_Price','Order_Value']].agg(['min','max','mean','median','std','sum'])

           Quantity    Unit_Price   Order_Value
min        1.000000  1.513300e+02  1.198900e+02
max        4.000000  2.499831e+04  9.769051e+04
mean       2.001000  1.227810e+04  1.893211e+04
median     2.000000  1.190312e+04  1.384561e+04
std        1.088202  7.232055e+03  1.642771e+04
sum     2001.000000  1.227810e+07  1.893211e+07

## Task 53

Create a pivot table showing total Order_Value by Region and Payment_Method.

In [126]:
pd.pivot_table(df,values='Order_Value',index='Region',columns='Payment_Method',aggfunc=sum)

Payment_Method,Cash on Delivery,Credit Card,Debit Card,EMI,UPI
Region,,,,,
Central,652235.60,736050.32,1019061.39,798894.40,837067.76
East,648780.87,691975.63,676714.64,604843.43,741542.27
North,454743.45,997035.51,958527.72,642317.36,1069741.10
South,644579.37,548632.03,612397.91,638794.46,748175.87
West,800862.11,781671.25,885836.53,872265.41,869367.37

## Task 54

Create a pivot table showing average Unit_Price by Product_Category and Customer_Segment.

In [127]:
pd.pivot_table(df,values='Unit_Price',index='Product_Category',columns='Customer_Segment',aggfunc='mean')

Customer_Segment     Corporate    Gift Buyer  Interior Designer   Residential
Product_Category
Curtains          13497.696250  13033.177805       10471.071897  11934.701724
Decor Pieces      14027.724595  11743.487273       11116.875641  11903.632982
Lighting          12724.674318  12544.726667       11763.694773  12393.503036
Rugs              11599.596364  12859.936429       13308.944500  11696.728333
Wall Art          13046.775962  12014.814667       11788.195965  12758.925333

## Task 55

Count the number of orders placed in each month.

In [129]:
df.groupby(df['Order_Date'].dt.month_name())['Order_ID'].count()

Order_Date
April        67
August       88
December     92
February     76
January      87
July         70
June         69
March        96
May          95
November     92
October      87
September    81
Name: Order_ID, dtype: int64

## Task 56

Find the month with the highest total sales.

In [136]:
df.groupby(df['Order_Date'].dt.month_name())['Order_Value'].sum().sort_values(ascending=False).head(1)

Order_Date
November    2034367.47
Name: Order_Value, dtype: float64

## Task 57

Find the region with the highest average order value.

In [138]:
df.groupby('Region')['Order_Value'].max().sort_values(ascending=False).head(1)

Region
East    97690.51
Name: Order_Value, dtype: float64

## Task 58

Find the product category with the highest total quantity sold.

In [141]:
df.groupby('Product_Category')['Quantity'].sum().sort_values(ascending=False).head(1)

Product_Category
Rugs    463
Name: Quantity, dtype: int64

## Task 59

Use query() to filter rows where Quantity >= 2 and Discount_Percent >= 15.

In [142]:
df.query('Quantity >= 2 and Discount_Percent >= 15').head(10)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Discount_Percent,Gross_Value,Discount_Amount,High_Value_Order
0,08ORD100522,2025-06-02,Interior Designer,West,Decor Pieces,Cash on Delivery,3,2003.04,24,4566.93,2025,6,0,24,6009.12,1442.19,No
5,08ORD100679,2024-11-19,Residential,Central,Curtains,Debit Card,2,17048.48,35,22163.02,2024,11,1,35,34096.96,11933.94,Yes
9,08ORD100137,2025-03-06,Corporate,East,Rugs,Credit Card,2,14365.42,38,17813.12,2025,3,3,38,28730.84,10917.72,Yes
15,08ORD100900,2025-01-02,Gift Buyer,East,Decor Pieces,Debit Card,2,24009.62,32,32653.08,2025,1,3,32,48019.24,15366.16,Yes
17,08ORD100884,2025-07-17,Gift Buyer,West,Decor Pieces,UPI,3,16775.58,28,36235.25,2025,7,3,28,50326.74,14091.49,Yes
18,08ORD100762,2025-10-20,Interior Designer,West,Rugs,Cash on Delivery,2,18761.58,35,24390.05,2025,10,0,35,37523.16,13133.11,Yes
21,08ORD100175,2025-07-08,Corporate,South,Wall Art,UPI,4,11316.98,22,35308.98,2025,7,1,22,45267.92,9958.94,Yes
23,08ORD100528,2025-09-30,Gift Buyer,Central,Rugs,Credit Card,4,2872.24,34,7582.71,2025,9,1,34,11488.96,3906.25,Yes
25,08ORD100236,2024-07-24,Interior Designer,North,Lighting,Credit Card,2,20904.13,26,30938.11,2024,7,2,26,41808.26,10870.15,Yes
27,08ORD100987,2025-12-25,Gift Buyer,West,Wall Art,EMI,3,17140.05,19,41650.32,2025,12,3,19,51420.15,9769.83,Yes

## Task 60

Select only Order_ID, Region, Product_Category, and Order_Value columns.

In [144]:
df[['Order_ID','Region','Product_Category','Order_Value']].head(20)

       Order_ID   Region Product_Category  Order_Value
0   08ORD100522     West     Decor Pieces      4566.93
1   08ORD100738     West         Wall Art     16188.24
2   08ORD100741     West         Wall Art     20567.80
3   08ORD100661    South             Rugs      8529.00
4   08ORD100412     West         Wall Art      3731.33
5   08ORD100679  Central         Curtains     22163.02
6   08ORD100627  Central     Decor Pieces      5347.95
7   08ORD100514  Central         Curtains     24065.86
8   08ORD100860     East         Wall Art      6211.55
9   08ORD100137     East             Rugs     17813.12
10  08ORD100812    North         Curtains      3167.33
11  08ORD100077     East             Rugs      7810.70
12  08ORD100637     East             Rugs     15342.16
13  08ORD100974     East         Lighting       368.22
14  08ORD100939    North         Lighting     21820.20
15  08ORD100900     East     Decor Pieces     32653.08
16  08ORD100281     East     Decor Pieces     10208.87
17  08ORD100884     West     Decor Pieces     36235.25
18  08ORD100762     West             Rugs     24390.05
19  08ORD100320    North     Decor Pieces     27578.25

## Task 61

Reorder the columns in any meaningful custom order.

In [148]:
df[['Order_ID','Order_Date','Region','Customer_Segment','Product_Category','Payment_Method','Quantity','Unit_Price','Discount_Percent','Order_Value']]

,Order_ID,Order_Date,Region,Customer_Segment,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Discount_Percent,Order_Value
0,08ORD100522,2025-06-02,West,Interior Designer,Decor Pieces,Cash on Delivery,3,2003.04,24,24,4566.93
1,08ORD100738,2025-01-08,West,Interior Designer,Wall Art,Debit Card,3,6131.91,12,12,16188.24
2,08ORD100741,2025-09-24,West,Residential,Wall Art,Cash on Delivery,2,10940.32,6,6,20567.80
3,08ORD100661,2024-09-06,South,Residential,Rugs,Debit Card,1,9917.44,14,14,8529.00
4,08ORD100412,2024-03-25,West,Corporate,Wall Art,Debit Card,1,4145.92,10,10,3731.33
...,...,...,...,...,...,...,...,...,...,...,...
995,08ORD100107,2025-08-18,West,Interior Designer,Decor Pieces,Debit Card,2,3384.99,8,8,6228.38
996,08ORD100271,2025-05-15,Central,Corporate,Rugs,UPI,1,2269.52,10,10,2042.57
997,08ORD100861,2024-09-12,North,Interior Designer,Wall Art,UPI,1,13990.14,1,1,13850.24
998,08ORD100436,2024-05-15,West,Corporate,Curtains,EMI,1,16820.17,29,29,11942.32
999,08ORD100103,2025-05-03,East,Interior Designer,Rugs,UPI,3,21462.87,23,23,49579.23

## Task 62

Find rows where Order_Value is above the overall average order value.

In [ ]:
df['Order_Value']

## Task 63

Find rows where Unit_Price is below the 25th percentile.

## Task 64

Find the correlation between Quantity, Unit_Price, Discount_Percent, and Order_Value.

## Task 65

Export the top 50 highest value orders to a CSV file.

## Task 66

Create a bar chart of total Order_Value by Region using Matplotlib.

## Task 67

Create a bar chart of total Quantity sold by Product_Category using Seaborn.

## Task 68

Create a histogram of Unit_Price using Matplotlib.

## Task 69

Create a histogram of Order_Value with KDE using Seaborn.

## Task 70

Create a boxplot of Order_Value by Region.

## Task 71

Create a boxplot of Unit_Price by Payment_Method.

## Task 72

Create a countplot of Customer_Segment.

## Task 73

Create a pie chart of Payment_Method distribution.

## Task 74

Create a line chart of monthly total sales.

## Task 75

Create a heatmap of correlation among numerical columns.

## Task 76

Create a scatter plot of Unit_Price vs Order_Value.

## Task 77

Create a scatter plot of Quantity vs Order_Value colored by Region using Seaborn.

## Task 78

Create a violin plot of Order_Value by Product_Category.

## Task 79

Create a stacked bar style plot of monthly sales by Region.

## Task 80

Create a pairplot for Quantity, Unit_Price, Discount_Percent, and Order_Value.